name: flutter_ai_scanner
description: "AI-powered flutter package for document and image scanning with fast, accurate text recognition and OCR using Openai."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/flutter_ai_scanner.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: